### ISSUE TITLE
Huge complaint!

### ISSUE THREAD

**Issue by tobbenb** [linuxserver/new-project-templates#4]
[![linuxserver.io](https://www.linuxserver.io/wp-content/uploads/2015/06/linuxserver_medium.png)](https://linuxserver.io)
##   Submission guide for issues, help us to help you.

Please provide us with the following information
- Host OS
- Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings.
- Docker log output, docker log <container-name>
- Mention if you're using symlinks on any of the volume mounts.

Can I delete the above?

**Comment by sparklyballs** [comment]
no, or i'll track you down and inject you with the blood of a swedish orphan.

**Comment by tobbenb** [comment]
On that note, I'll close the nonexisting issue...
